### ISSUE TITLE
Exception thrown while saving Template 

### ISSUE THREAD

**Issue by brian-labelle** [magespecialist/notifier-template#1]
According to the docs, a template name can be in the format
event:event_name_here

The field comment says "Events specific templates must be identified as "event:event_name", e.g.: "event:admin_user_authenticate_after""

I tried creating a template with the identifier `event:sales_order_place_after` and an `\InvalidExceptionArgument` was thrown by `\MSP\NotifierTemplate\Model\DatabaseTemplate\Validator\CodeValidator::execute` because my identifier does not match the regex `/^[\w_]+$/`

Perhaps we can use `/^(event:|[\w_]+)+$/` for the regex?

**Comment by phoenix128** [comment]
Should be `/^(\w+:)?[\w_]+$/`. "event" is a prefix coming from `msp/module-notifier-event` and in order to keep a DDD pattern, this module could not be aware of the other module existence.

In this way we leave the possibility of defining "special prefixes" for custom purposes.

Fixing it right now.

**Comment by phoenix128** [comment]
Fixed in 0.1.2
